### ISSUE TITLE
[ BUG | SendTimestamps could not be constructed ]

### ISSUE THREAD

**Issue by ThunderMite42** [Taimoor-Tariq/BetterDiscordStuff#57] opened 2022-09-21 17:35 UTC
This is similar to other installation issues, but the exact error text is different (as shown in the screenshot):
```
TypeError: Cannot read property 'locale' of undefined
    at new SendTimestamp (betterdiscord://plugins/SendTimestamps.plugin.js:226:59)
    at Object.initializeAddon (<anonymous>:4:41592)
    at Object.loadAddon (<anonymous>:4:9075)
    at Object.loadAddon (<anonymous>:4:40847)
    at FSWatcher.<anonymous> (<anonymous>:4:7059)
```

![image](https://user-images.githubusercontent.com/38893728/191566456-f5ff54a6-2b3c-4973-af60-5f7c1a1c4179.png)

**Comment by Fusezion** [comment] 2022-09-21 19:00
Duplicate of #51

**Comment by Fusezion** [comment] 2022-09-21 19:01
While the error is different its still a duplicate the answer to fix is also in that issue

**Comment by Taimoor-Tariq** [comment] 2022-10-17 16:59
I will fix this in the next update ❤️

**Closed as completed by Taimoor-Tariq** 2022-10-17 16:59 UTC
