### ISSUE TITLE
[ BUG | SendTimestamps ] ...

### ISSUE THREAD

**Issue by Fxnarji** [Taimoor-Tariq/BetterDiscordStuff#56] opened 2022-09-15 16:45 UTC
**Issue**
when trying to install the plugin, i get the following error msg:
TypeError: Cannot read property 'locale' of undefined
    at new SendTimestamp (betterdiscord://plugins/SendTimestamps.plugin.js:226:59)
    at Object.initializeAddon (<anonymous>:4:41592)
    at Object.loadAddon (<anonymous>:4:9075)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.updateList (<anonymous>:4:10713)
    at Object.updatePluginList (<anonymous>:4:40544)
    at O.reload (<anonymous>:4:108624)
    at Object.Ye (https://discordapp.com/assets/33ea390649db9e20ae77.js:6132:658)
    at qe (https://discordapp.com/assets/33ea390649db9e20ae77.js:6132:812)
    at https://discordapp.com/assets/33ea390649db9e20ae77.js:6152:409
    at Pr (https://discordapp.com/assets/33ea390649db9e20ae77.js:6152:506)
    at Mr (https://discordapp.com/assets/33ea390649db9e20ae77.js:6152:920)
    at https://discordapp.com/assets/33ea390649db9e20ae77.js:6158:680
    at ke (https://discordapp.com/assets/33ea390649db9e20ae77.js:6240:404)
    at https://discordapp.com/assets/33ea390649db9e20ae77.js:6154:395
    at Br (https://discordapp.com/assets/33ea390649db9e20ae77.js:6154:425)
    at rn (https://discordapp.com/assets/33ea390649db9e20ae77.js:6141:757)
    at nn (https://discordapp.com/assets/33ea390649db9e20ae77.js:6141:7)
    at t.unstable_runWithPriority (https://discordapp.com/assets/33ea390649db9e20ae77.js:6352:828)
    at Ki (https://discordapp.com/assets/33ea390649db9e20ae77.js:6163:117)
    at Ue (https://discordapp.com/assets/33ea390649db9e20ae77.js:6240:144)
    at en (https://discordapp.com/assets/33ea390649db9e20ae77.js:6140:800)
    at HTMLDivElement.r (https://discordapp.com/assets/8654157bdfcd1f0bc155.js:126:559)

[optional but helpful: screenshots, plugin config]
![image](https://user-images.githubusercontent.com/92873527/190460671-b05c274c-5ab6-4aab-b330-66263487518e.png)

**Comment by Fusezion** [comment] 2022-09-17 05:56
Duplicate of #51

**Comment by Taimoor-Tariq** [comment] 2022-10-17 16:59
Duplicate of #51

**Closed as completed by Taimoor-Tariq** 2022-10-17 16:59 UTC
