### ISSUE TITLE
[ BUG | SendTimestamps ] ...

### ISSUE THREAD

**Issue by ComiCherro** [Taimoor-Tariq/BetterDiscordStuff#54] opened 2022-08-29 22:06 UTC
when installing the plugin better discord says it could not be constructed
here is the js error:
TypeError: Cannot read property 'locale' of undefined
    at new SendTimestamp (betterdiscord://plugins/SendTimestamps.plugin.js:226:59)
    at Object.initializeAddon (<anonymous>:4:41592)
    at Object.loadAddon (<anonymous>:4:9075)
    at Object.loadAddon (<anonymous>:4:40847)
    at FSWatcher.<anonymous> (<anonymous>:4:7059)

**Comment by davidc1701** [comment] 2022-08-31 18:37
This is a duplicate of #51.

**Comment by Taimoor-Tariq** [comment] 2022-10-17 17:01
Duplicate of #51

**Closed as completed by Taimoor-Tariq** 2022-10-17 17:01 UTC
